
server:
  port : ${PORT:7030}

#management:
#   security:
#      enabled: false
#   endpoint:
#      health:
#        show-details: always


logging:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error